src/views.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session, current_app
import db as database
import re #for regex
import random
from flask_mail import Mail
from flask_mail import Message
from werkzeug.security import check_password_hash, generate_password_hash
from cryptography.fernet import Fernet

key = Fernet.generate_key()
fernet = Fernet(key)

views = Blueprint('views', __name__)

#regex used to check if an email is a valid format
regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,7}\b'

@views.route('/')
def home_redirect():
    return redirect('/home')

@views.route("/home")
def home():
    session.clear()
    return render_template("homepage.html")

@views.route("/login1", methods=('GET', 'POST'))
def login1():
    session.clear()
    if request.method == 'POST':
        email = request.form['email'] #get email from form

        error = None

        #check if email exists
        db = database.get_db()
        usernamecheck = db.execute('SELECT COUNT(*) FROM user WHERE username = ?', (email,)).fetchone()
        if (usernamecheck[0] == 0):
            error = "username doesn't exists"

        #checking if email is valid
        if(not re.fullmatch(regex, email)): 
            error = "not valid email"

        if error is None:
            session['username'] = email #session so that email can be accessed on login2
            return redirect(url_for('views.login2'))

        flash(error) #display errors on current page
        
    return render_template("login1.html")

@views.route("/login2", methods=('GET', 'POST'))
def login2():
    #if user tried to skip login1
    if session.get('username') is None:
        return redirect(url_for('views.home'))
    
    user = session.get('username')
    
    db = database.get_db() #create database connection

    #get users images
    getimages = db.execute('SELECT images FROM user WHERE username = ?', (user,)).fetchone()
    images = getimages[0]

    images = str(images)

    #store users images ids in a list
    imgIDList = []
    for i in range(0,18,2):
        temp = images[i:i+2]
        imgIDList.append(int(temp))

    #store users images srcs in a list
    imgSrcList = []
    for i in range(9):
        src = db.execute('SELECT src FROM images WHERE id = ?', (imgIDList[i],)).fetchone()
        imgSrcList.append(src[0])

    #randomize the images, keeping same index pairs
    zipped = list(zip(imgIDList, imgSrcList))
    random.shuffle(zipped)
    imgIDList, imgSrcList = zip(*zipped)

    #check if account is locked
    locksquery = db.execute('SELECT locked FROM user WHERE username = ?', (user,)).fetchone()
    if(locksquery[0] == 1):
        flash('account locked')
        return redirect(url_for('views.forgot'))

    if request.method == 'POST':
        password = request.form['password']

        error = None

        #get users current remaining attempts
        attemptsquery = db.execute('SELECT attempts FROM user WHERE username = ?', (user,)).fetchone()
        attempts = attemptsquery[0]
        
        #check if password is correct
        pwcheck = db.execute('SELECT pw FROM user WHERE username = ?', (user,)).fetchone()
        if(not check_password_hash(pwcheck[0], password)):
            error = "incorrect password"
            attempts = attempts-1
            db.execute('UPDATE user SET attempts = ? WHERE username = ?', (attempts, user,))
            db.commit()

        #if user is out of attempts - lock account
        if(attempts == 0):
            db.execute('UPDATE user SET locked = 1 WHERE username = ?', (user,))
            db.commit()
            flash('account locked')
            return redirect(url_for('views.forgot'))

        #if password is correct
        if error is None:
            session['password'] = password #set for target
            return redirect(url_for('views.target'))
        
        flash(error + ': ' + str(attempts) + ' attempts left')

    return render_template("login2.html", imgIDList=imgIDList, imgSrcList=imgSrcList)

@views.route("/signup1", methods=('GET', 'POST'))
def signup1():
    session.clear()
    if request.method == 'POST':
        email = request.form['email']
        fname = request.form['firstname']
        lname = request.form['lastname']

        error = None

        #check if email exists
        db = database.get_db()
        usernamecheck = db.execute('SELECT COUNT(*) FROM user WHERE username = ?', (email,)).fetchone()
        if (usernamecheck[0] != 0):
            error = "username already exists"

        if (not re.fullmatch(regex, email)):
            error = "not valid email"
        elif not fname:
            error = 'first name is required'
        elif not lname:
            error = 'last name is required'

        if error is None:
            session['username'] = email
            session['fname'] = fname
            session['lname'] = lname
            return redirect(url_for("views.signup2"))
        
        flash(error)

    return render_template("signup1.html")

@views.route("/signup2", methods=('GET', 'POST'))
def signup2():
    #if user tried to skip signup1 or has already been logged in
    if session.get('username') is None:
        return redirect(url_for('views.home'))
    if session.get('target') is not None:
        return redirect(url_for('views.target'))
    
    if request.method == 'POST':
        password = request.form['password']

        session['password'] = password

        return redirect(url_for('views.signup3'))
    
    #generate random image IDs
    imgIDList = []
    while(len(imgIDList) < 9):
        rand = random.randint(10,36) #make sure no duplicates
        if rand not in imgIDList:
            imgIDList.append(rand)

    db = database.get_db()

    #use random image IDs and get their src value
    imgSrcList = []
    for i in range(9):
        src = db.execute('SELECT src FROM images WHERE id = ?', (imgIDList[i],)).fetchone()
        imgSrcList.append(src[0])

    session['imgIDs'] = imgIDList #so we can access their ids and store them on signup3
    session['imgSrc'] = imgSrcList

    return render_template("signup2.html", imgIDList=imgIDList, imgSrcList=imgSrcList)

@views.route("/signup3", methods=('GET', 'POST'))
def signup3():
    #if user has tried to skip signup1 or signup2 or is already logged in
    if session.get('username') is None:
        return redirect(url_for('views.home'))
    if session.get('password') is None:
        return redirect(url_for('views.signup2'))
    if session.get('target') is not None:
        return redirect(url_for('views.target'))
    
    user = session.get('username')
    fname = session.get('fname')
    lname = session.get('lname')
    password = session.get('password')

    imgIDList = session.get('imgIDs')
    imgSrcList = session.get('imgSrc')

    #shuffle ids and srcs, keeping matching indexes
    zipped = list(zip(imgIDList, imgSrcList))
    random.shuffle(zipped)
    imgIDList, imgSrcList = zip(*zipped)

    if request.method == 'POST':
        allIDs = "" #will store a concatenated version of users images ids
        for i in range(len(imgIDList)): 
            allIDs = allIDs + str(imgIDList[i])

        second_password = request.form['password']
        if (int(password) == int(second_password)): #if passwords match
            db = database.get_db()
            if session.get('reset') is not None:
                db.execute('UPDATE user SET pw = ?, images = ?, attempts = ?, locked = ? WHERE username = ?', (generate_password_hash(password), allIDs, 4, 0, user))
                db.commit()
                return redirect(url_for('views.target'))
            else:
                db.execute('INSERT INTO user (username, fname, lname, pw, attempts, locked, images) VALUES (?, ?, ?, ?, 4, 0, ?)', (user, fname, lname, generate_password_hash(password), allIDs))
                db.commit()
                return redirect(url_for('views.target'))
        else:
            session.pop('password')
            flash('password confirmation wrong - retry')
            return redirect(url_for('views.signup2'))

    return render_template("signup3.html", imgIDList=imgIDList, imgSrcList=imgSrcList)

@views.route("/forgot", methods=('GET', 'POST'))
def forgot():

    session.clear()

    mail = Mail(current_app)

    if request.method == 'POST':
        email = request.form['email']

        msg = Message("Password Reset for Graphical Passwords", sender="graphicalpws@gmail.com", recipients=[email])
        
        db = database.get_db()

        id = db.execute('SELECT id FROM user WHERE username = ?', (email,)).fetchone()
        
        encID = fernet.encrypt(str(id[0]).encode())
        encID = str(encID)
        sendEnc = encID[2:len(encID)-1]

        msg.body = """
        Click the link to reset your password
        http://127.0.0.1:5000/reset/{}""".format(sendEnc)
        mail.send(msg)

    return render_template("forgot.html")

@views.route("/target")
def target():
    #if user is not logged in
    if session.get('username') is None:
        return redirect(url_for('views.home'))
    if session.get('password') is None:
        return redirect(url_for('views.signup2'))
    session['target'] = 'set' #user has reached the target page and is logged in - cannot go back to signup2 or signup3
    
    #set users attempts back to 4
    db = database.get_db()
    db.execute('UPDATE user SET attempts = 4 WHERE username = ?', (session['username'],))
    db.commit()
    
    return render_template("target.html")

@views.route("/logout")
def logout():
    session.clear()
    return redirect(url_for('views.home'))

@views.route("/reset/<id>", methods=('GET', 'POST'))
def reset(id):

    db = database.get_db()

    res = bytes(id, 'utf-8')
    decID = fernet.decrypt(res).decode()

    username = db.execute('SELECT username FROM user WHERE id = ?', (decID,)).fetchone()
    fname = db.execute('SELECT fname FROM user WHERE id = ?', (decID,)).fetchone()

src/templates/forgot.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/style.css') }}">
    <title>Forgot</title>
</head>
<body>
    {% for message in get_flashed_messages() %}
        <div class="flash">{{ message }}</div>
    {% endfor %}
    <div id="forgot-image"><img src="../static/imgs/RP.png" alt="singup"/></div>

    <div id="forgot-white">
        <form method="POST">
            <div id="forgot-email">
                <input id="forgot-textbox" type="text" id="email" name="email" placeholder="Enter Email..">
            </div>

            <div id="forgot-buttons">
                <button class="button" id="forgot-button" type="submit">Reset Password</button>
            </div>
        </form>

        <p id="forgot-select">You will be sent an email with instructions to reset your password</p>
    </div>

</body>
</html>

src/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/style.css') }}">
    <title>Home</title>
</head>
<body>

    <div id="homepage-image"><img src="../static/imgs/gpass.png" alt="gpass"/></div>

    <div id="homepage-white">
        <div id="homepage-buttons">
            <a href="{{ url_for('views.login1') }}"><button class="button" id="homepage-button" type="button">Login</button></a> </br>
            <a href="{{ url_for('views.signup1') }}"><button class="button" id="homepage-button" type="button">Sign-Up</button></a>
        </div>
    </div>

</body>
</html>

src/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/style.css') }}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
{% endfor %}
{% block content %}{% endblock %}
</body>
</html>

src/templates/login1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/style.css') }}">
    <title>Login</title>
</head>
<body>
    {% for message in get_flashed_messages() %}
        <div class="flash">{{ message }}</div>
    {% endfor %}

    <div id="login1-image"><img src="../static/imgs/login.png" alt="login"/></div>

    <div id="login1-white">
        <div id="login1-email">

            <form method="POST">
                <input id="login1-textbox" type="text" id="email" oninput="this.value = this.value.toLowerCase()" name="email" placeholder="Enter Email..">
                <div id="login1-buttons">
                    <button class="button" id="login1-button" type="submit">Enter</button>
                </div>
            </form>

        </div>
        
    </div>

</body>
</html>

src/templates/login2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/style.css') }}">
    <title>Login</title>
</head>
<body>
    {% for message in get_flashed_messages() %}
        <div class="flash">{{ message }}</div>
    {% endfor %}

    <div id="login2-image"><img src="../static/imgs/login.png" alt="login"/></div>

    <div id="login2-white">
        <img id= "settings" class="login2-setting settings" src="../static/imgs/settings.png"/>
        <div id="settings-window">
            <label>
              <input type="checkbox" id="text-mode" onchange="handleModes(true)">Text Mode
            </label>
            <br>
            <label>
              <input type="checkbox" id="colorblind-mode" onchange="handleModes(false)">Colorblind Mode
            </label>
        </div>
        <img id="reset" class="login2-setting reset" src="../static/imgs/reset.png"/>

        <img id="login2-select" src="../static/imgs/Eyp.png" width="300" height="55" alt="Enter your password">
        
        <form method="POST">
            <div id="login2-images">
                <div class="image">
                    <img class="login2-buttons" src="{{ imgSrcList[0] }}" data-number="{{ imgIDList[0] }}" data-section="0">
                </div>
                <div class="image">
                    <img class="login2-buttons" src="{{ imgSrcList[1] }}" data-number="{{ imgIDList[1] }}" data-section="1">
                </div>
                <div class="image">
                    <img class="login2-buttons" src="{{ imgSrcList[2] }}" data-number="{{ imgIDList[2] }}" data-section="2">
                </div>
                <div class="image">
                    <img class="login2-buttons" src="{{ imgSrcList[3] }}" data-number="{{ imgIDList[3] }}" data-section="3">
                </div>
                <div class="image">
                    <img class="login2-buttons" src="{{ imgSrcList[4] }}" data-number="{{ imgIDList[4] }}" data-section="4">
                </div>
                <div class="image">
                    <img class="login2-buttons" src="{{ imgSrcList[5] }}" data-number="{{ imgIDList[5] }}" data-section="5">
                </div>
                <div class="image">
                    <img class="login2-buttons" src="{{ imgSrcList[6] }}" data-number="{{ imgIDList[6] }}" data-section="6">
                </div>
                <div class="image">
                    <img class="login2-buttons" src="{{ imgSrcList[7] }}" data-number="{{ imgIDList[7] }}" data-section="7">
                </div>
                <div class="image">
                    <img class="login2-buttons" src="{{ imgSrcList[8] }}" data-number="{{ imgIDList[8] }}" data-section="8">
                </div>
            </div>
            <div id="login2-confirm">
                <button class="button" id="login2-confirmbtn" type="submit">Confirm</button>
            </div>
            <input id="password" type="password" name="password" hidden>
        </form>

        <div id="login2-forgot">
            <a href="{{ url_for('views.forgot') }}">Forgot Password?</a>
        </div>

    </div>

    <script src="../static/javascript/login2.js"></script>

</body>
</html>

src/templates/signup1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/style.css') }}">
    <title>Signup</title>
</head>
<body>
    {% for message in get_flashed_messages() %}
        <div class="flash">{{ message }}</div>
    {% endfor %}
    
    <div id="signup1-image"><img src="../static/imgs/signup.png" alt="singup"/></div>

    <div id="signup1-white">

        <form method="POST">
            <div id="signup1-info">
                <input id="signup1-email" type="text" id="email" oninput="this.value = this.value.toLowerCase()" name="email" placeholder="Email.."> </br>
                <input id="signup1-textboxname" type="text" id="fname" name="firstname" placeholder="First Name..">
                <input id="signup1-textboxname" type="text" id="lname" name="lastname" placeholder="Last Name..">
            </div>
            <div id="signup1-buttons">
                <button class="button" id="signup1-button" type="submit">Register</button>
            </div>
        </form>
    </div>

</body>
</html>

src/templates/signup2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/style.css') }}">
    <title>Signup</title>
</head>
<body>
    {% for message in get_flashed_messages() %}
        <div class="flash">{{ message }}</div>
    {% endfor %}

    <div id="signup2-image"><img src="../static/imgs/signup.png" alt="singup"/></div>

    <div id="signup2-white">
        <img id= "settings" class="signup2-setting settings" src="../static/imgs/settings.png"/>
        <div id="settings-window">
            <label>
              <input type="checkbox" id="text-mode" onchange="handleModes(true)">Text Mode
            </label>
            <br>
            <label>
              <input type="checkbox" id="colorblind-mode" onchange="handleModes(false)">Colorblind Mode
            </label>
        </div>
        <img id="reset" class="signup2-setting reset" src="../static/imgs/reset.png"/>
        <img id="signup2-select" src="../static/imgs/Eyp.png" width="300" height="55" alt="Enter your password">

        <form method="POST">
            <div id="signup2-images">
                <div class="image">
                    <img class="signup2-buttons" src="{{ imgSrcList[0] }}" data-number="{{ imgIDList[0] }}" data-section="0">
                </div>
                <div class="image">
                    <img class="signup2-buttons" src="{{ imgSrcList[1] }}" data-number="{{ imgIDList[1] }}" data-section="1">
                </div>
                <div class="image">
                    <img class="signup2-buttons" src="{{ imgSrcList[2] }}" data-number="{{ imgIDList[2] }}" data-section="2">
                </div>
                <div class="image">
                    <img class="signup2-buttons" src="{{ imgSrcList[3] }}" data-number="{{ imgIDList[3] }}" data-section="3">
                </div>
                <div class="image">
                    <img class="signup2-buttons" src="{{ imgSrcList[4] }}" data-number="{{ imgIDList[4] }}" data-section="4">
                </div>
                <div class="image">
                    <img class="signup2-buttons" src="{{ imgSrcList[5] }}" data-number="{{ imgIDList[5] }}" data-section="5">
                </div>
                <div class="image">
                    <img class="signup2-buttons" src="{{ imgSrcList[6] }}" data-number="{{ imgIDList[6] }}" data-section="6">
                </div>
                <div class="image">
                    <img class="signup2-buttons" src="{{ imgSrcList[7] }}" data-number="{{ imgIDList[7] }}" data-section="7">
                </div>
                <div class="image">
                    <img class="signup2-buttons" src="{{ imgSrcList[8] }}" data-number="{{ imgIDList[8] }}" data-section="8">
                </div>
            </div>
            <div id="signup2-confirm">
                <button class="button" id="signup2-confirmbtn" type="submit">Confirm</button>
            </div>
            <input id="password" type="password" name="password" hidden>
        </form>

        <div id="signup2-refresh">
            <a href="{{ url_for('views.signup2') }}"><button class="button" id="signup2-refreshbtn" type="button">Refresh images</button></a>
        </div>

        <script src="../static/javascript/signup2.js"></script>

    </div>

</body>
</html>

src/templates/signup3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/style.css') }}">
    <title>Signup</title>
</head>
<body>
    <div id="signup3-image"><img src="../static/imgs/signup.png" alt="singup"/></div>

    <div id="signup3-white">
        <img id= "settings" class="signup3-setting settings" src="../static/imgs/settings.png"/>
        <div id="settings-window">
            <label>
              <input type="checkbox" id="text-mode" onchange="handleModes(true)">Text Mode
            </label>
            <br>
            <label>
              <input type="checkbox" id="colorblind-mode" onchange="handleModes(false)">Colorblind Mode
            </label>
        </div>
        <img id="reset" class="signup3-setting reset" src="../static/imgs/reset.png"/>
        <img id="signup3-select" src="../static/imgs/Reyp.png" width="300" height="55" alt="Re-enter your password">

        <form method="POST">
            <div id="signup3-images">
                <div class="image">
                    <img class="signup3-buttons" src="{{ imgSrcList[0] }}" data-number="{{ imgIDList[0] }}" data-section="0">
                </div>
                <div class="image">
                    <img class="signup3-buttons" src="{{ imgSrcList[1] }}" data-number="{{ imgIDList[1] }}" data-section="1">
                </div>
                <div class="image">
                    <img class="signup3-buttons" src="{{ imgSrcList[2] }}" data-number="{{ imgIDList[2] }}" data-section="2">
                </div>
                <div class="image">
                    <img class="signup3-buttons" src="{{ imgSrcList[3] }}" data-number="{{ imgIDList[3] }}" data-section="3">
                </div>
                <div class="image">
                    <img class="signup3-buttons" src="{{ imgSrcList[4] }}" data-number="{{ imgIDList[4] }}" data-section="4">
                </div>
                <div class="image">
                    <img class="signup3-buttons" src="{{ imgSrcList[5] }}" data-number="{{ imgIDList[5] }}" data-section="5">
                </div>
                <div class="image">
                    <img class="signup3-buttons" src="{{ imgSrcList[6] }}" data-number="{{ imgIDList[6] }}" data-section="6">
                </div>
                <div class="image">
                    <img class="signup3-buttons" src="{{ imgSrcList[7] }}" data-number="{{ imgIDList[7] }}" data-section="7">
                </div>
                <div class="image">
                    <img class="signup3-buttons" src="{{ imgSrcList[8] }}" data-number="{{ imgIDList[8] }}" data-section="8">
                </div>
            </div>
            <div id="signup3-confirm">
                <button class="button" id="signup3-confirmbtn" type="submit">Confirm</button>
            </div>
            <input id="password" type="password" name="password" hidden>
        </form>

        <script src="../static/javascript/signup3.js"></script>

    </div>
</body>
</html>

src/templates/target.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/style.css') }}">
    <title>Target</title>
</head>
<body>

    <div id="login2-image"><img src="../static/imgs/logged.png" alt="logged"/></div>
    </br>
    <a style="font-size: 20pt;" id="logout" href="{{ url_for('views.logout') }}">Logout</a>

</body>
</html>